openapi: 3.0.0
info:
  title: "Hotshots REST API"
  description: "An API for Hotshots court scores."
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Game:
      type: "object"
      required:
        - courtname
      properties:
        courtname:
          type: "string"
        team1:
          type: "string"
        team2:
          type: "string"
        score1:
          type: "integer"
        score2:
          type: "integer"
        gamenum:
          type: "integer"
  parameters:
    courtname:
      name: "courtname"
      description: "Letter of Hotshots court"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /games:
    get:
      operationId: "games.read_all"
      tags:
        - "Games"
      summary: "Read the list of games on each court."
      responses:
        "200":
          description: "Successfully read games list"
    post:
      operationId: "games.create"
      tags:
        - Games
      summary: "Create a game"
      requestBody:
          description: "Game to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "game"
                $ref: "#/components/schemas/Game"
      responses:
        "201":
          description: "Successfully created game"
  /games/{courtname}:
    get:
      operationId: "games.read_one"
      tags:
        - Games
      summary: "Read one game"
      parameters:
        - $ref: "#/components/parameters/courtname"
      responses:
        "200":
          description: "Successfully read game"
    put:
      tags:
        - Games
      operationId: "games.update"
      summary: "Update a game"
      parameters:
        - $ref: "#/components/parameters/courtname"
      responses:
        "200":
          description: "Successfully updated game"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "game"
              $ref: "#/components/schemas/Game"
    delete:
      tags:
        - Games
      operationId: "games.delete"
      summary: "Delete a game"
      parameters:
        - $ref: "#/components/parameters/courtname"
      responses:
        "204":
          description: "Successfully deleted game"
